export { crearCartaHMTL } from './crear-carta-html.js'
export { crearDeck } from './create-deck.js'
export { pedirCarta } from './pedir-carta.js'
export { turnoComputadora } from './turno-computadora.js'
export { valorCarta } from './valor-carta.js'